# Spark Application Configuration
spark.master                  yarn
spark.submit.deployMode       client

# YARN Configuration
spark.yarn.submit.waitAppCompletion    true
spark.hadoop.yarn.resourcemanager.address  172.20.0.4:8032
spark.hadoop.yarn.resourcemanager.scheduler.address  172.20.0.4:8030
spark.hadoop.yarn.resourcemanager.resource-tracker.address  172.20.0.4:8031
spark.hadoop.yarn.resourcemanager.admin.address  172.20.0.4:8033
spark.hadoop.yarn.resourcemanager.webapp.address  172.20.0.4:8088

# Memory Configuration
spark.driver.memory           2g
spark.executor.memory         2g

# Executor Configuration
spark.executor.cores          2
spark.executor.instances      2

# Hive Configuration
spark.sql.catalogImplementation  hive
spark.sql.warehouse.dir       /user/hive/warehouse
spark.hadoop.hive.metastore.uris  thrift://hivemetastore:9083

# File System Configuration
spark.hadoop.fs.defaultFS     hdfs://namenode:9000