services:
  base:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: hadoop-base:latest
    hostname: base

  namenode:
    build:
      context: ./namenode
      dockerfile: Dockerfile
    image: hadoop-namenode:latest
    depends_on:
      - base
    container_name: namenode
    hostname: namenode
    restart: on-failure
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      hadoop_network:
        ipv4_address: 172.20.0.2
    
  datanode:
    build:
      context: ./datanode
      dockerfile: Dockerfile
    image: hadoop-datanode:latest
    depends_on:
      - base
      - namenode
    container_name: datanode
    hostname: datanode
    restart: always
    ports:
      - 9864:9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      hadoop_network:
        ipv4_address: 172.20.0.3

networks:
  hadoop_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  hadoop_namenode:
  hadoop_datanode: